spring.application.name=ADDRESS

spring.datasource.url = jdbc:postgresql://localhost:5432/ADDRESS
spring.datasource.username = postgres
spring.datasource.password = Welcome@1234$

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update

server.port=8082

#TO specify that this is the server and no need to register itself
eureka.client.register-with-eureka=true

#TO tell the server, no need to look up other services as this is the server
#and not the client, which needs to fetch details of other services for communication
eureka.client.fetch-registry=true

#Defines the Eureka Server URL where clients should register themselves or fetch registry info from
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#Defines the hostname that will be registered with Eureka for this Service
#Other services will use this hostname when they want to call this service
eureka.instance.hostname=localhost